name: pytest
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    types: [opened]
  schedule:
    - cron: '*/5 * * * *'


jobs:  
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: pre -checkout
        run: |
          pwd
          ls -lh
      - name: checkout using action
        uses: actions/checkout@v3
      - name: after checkout
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
